### ISSUE TITLE
TypeError: table.getFirst(...) is null

### ISSUE THREAD

**Issue by Deesen** [pmfx/CategorizedTabs#1]
I´m not sure why but I get this error when trying to use this plugin. Replacing [Line 166](https://github.com/pmfx/CategorizedTabs/blob/master/assets/plugins/categorizedtabs/ondocformrender.phtml#L166) with the following code helped me out:

    var first = table.getFirst();
    if(first == null) return;
    var rows = first.getChildren();

**Comment by Aharito** [comment]
@Deesen What version of MODx did you use when you get this error? I try this plugin on 1.2.1-d9.1.0 by Dmitry and everything is good.

**Comment by Aharito** [comment]
And note: I use non-default plugin config - TV tab: true;  Order tabs by category rank: true
Maybe this info will help the author in bugfix.
